EXP:
  seed: 0
  env_name: 'BottleFlip-v0'
SOLVER:
  n_iters: 500
  init_range: 
    v: ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0))
    p: ((0.15, 0.65, 0.5), (0.15, 0.65, 0.5))
  optim:
    type: 'Adam'
    lr: 1e-3
    beta_1: 0.9
    beta_2: 0.99
